-- The rates institutions declare each year, as the user's own record of them.
--
-- The app ships a catalogue of these in web/src/lib/institutions.js, which is
-- accurate on the day it is written and rots from there: ASNB declares ASB every
-- December, EPF every February, Tabung Haji in the first quarter. A file only a
-- release can change is the wrong home for a number that changes on a schedule.
--
-- So this table holds the user's rates and the catalogue becomes a DEFAULT. A row
-- here wins over the shipped figure for the same fund and year, which makes three
-- things possible that were not: correcting a shipped figure, adding a year the
-- app has not been updated for, and recording a fund the catalogue never had.
--
-- product_id is a catalogue id ('ASB', 'EPF_PERSARAAN') and deliberately carries
-- NO foreign key, because the thing it refers to lives in JavaScript rather than
-- in this database. That is a real seam: renaming a catalogue id orphans its
-- rows. The ids are treated as a stable published contract for that reason, and
-- institution_id is stored alongside so an orphan is still legible rather than
-- being a bare string nobody can place.
--
-- Rates are stored as DECLARED — a percent for EPF and Tabung Haji, sen per unit
-- for the ASNB funds — matching assets.rate_quote. The table does not know which
-- it is holding; the catalogue entry does, and assetRate() divides by 100 either
-- way because a fixed-price fund's unit is RM 1.00.

-- migrate:up

CREATE TABLE IF NOT EXISTS declared_rates (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_id TEXT NOT NULL,                 -- 'ASNB' | 'EPF' | 'TH', for legibility
  product_id     TEXT NOT NULL,                 -- catalogue id: 'ASB', 'EPF_PERSARAAN'
  year           INTEGER NOT NULL,              -- FINANCIAL year, not the year announced:
                                                -- ASB 2's 2026 is the year to 31 March 2026
  rate           DOUBLE PRECISION NOT NULL,     -- base, as declared
  bonus          DOUBLE PRECISION,              -- ASB's discretionary top-up; null for the rest
  shariah        DOUBLE PRECISION,              -- EPF's second series; null where there is only one
  note           TEXT NOT NULL DEFAULT '',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per fund per year. The upsert in the model relies on this.
CREATE UNIQUE INDEX IF NOT EXISTS declared_rates_product_year_idx
  ON declared_rates (product_id, year);

ALTER TABLE declared_rates DROP CONSTRAINT IF EXISTS declared_rates_year_check;
ALTER TABLE declared_rates ADD CONSTRAINT declared_rates_year_check
  CHECK (year BETWEEN 1990 AND 2200);

-- A declared rate is never negative. It CAN be zero: Tabung Haji has come close,
-- and a fund that pays nothing in a bad year is a fact worth recording rather
-- than an input to reject.
ALTER TABLE declared_rates DROP CONSTRAINT IF EXISTS declared_rates_rate_check;
ALTER TABLE declared_rates ADD CONSTRAINT declared_rates_rate_check
  CHECK (rate >= 0 AND (bonus IS NULL OR bonus >= 0) AND (shariah IS NULL OR shariah >= 0));

-- Sanity bound rather than a business rule. Anything past this is a typo — a
-- misplaced decimal turning 5.75 into 575 — and catching it here stops the
-- estimator projecting a 575% return with a straight face.
ALTER TABLE declared_rates DROP CONSTRAINT IF EXISTS declared_rates_sane_check;
ALTER TABLE declared_rates ADD CONSTRAINT declared_rates_sane_check
  CHECK (rate <= 100 AND (bonus IS NULL OR bonus <= 100) AND (shariah IS NULL OR shariah <= 100));

-- migrate:down

DROP INDEX IF EXISTS declared_rates_product_year_idx;
DROP TABLE IF EXISTS declared_rates;
