-- The rows a statement import reads and then throws away.
--
-- WHAT IS BEING LOST TODAY, exactly. `sync/parse_maybank_statement.py` and its
-- Node port both emit, per line, a posting date, a transaction date, the
-- merchant, where it happened, the amount, whether it was a credit, an
-- instalment's number-of-total, and — where the statement carried one — a
-- `foreign` block holding the original currency and amount. The ingest reads all
-- of that and keeps almost none of it. A booked line becomes an `expenses` row
-- whose date is `transacted || posted`, so whichever date did not win is gone;
-- the merchant survives only inside `expenses.note` as free text with the
-- location appended; and the foreign block is referenced nowhere in the service
-- at all. Every other line — an instalment billing, a payment, a rule-matched
-- commitment, a merchant nobody has written a rule for — is counted in a
-- response summary that is returned to the browser and never stored.
--
-- SO THE STATEMENT CANNOT BE RE-READ. Re-importing the same PDF is already
-- idempotent, which is a real property and the reason `ext_id` exists here too,
-- but idempotent is not the same as durable: the import proves nothing was
-- double-counted while keeping no record of what it saw. A question as ordinary
-- as "what did I actually buy on this card in July" has no table to ask.
--
-- WHY NOT WIDEN `expenses`. Because most of these rows are not expenses and must
-- never become them. An instalment billing is a plan's monthly line, already
-- counted through `card_plans`; a credit is a payment; a rule-matched line is
-- already subtracted from income as a commitment and booking it again would
-- count it twice — the service says so itself where it skips them. A table that
-- held all four would need `expenses` to grow a column meaning "do not treat
-- this as spending", which is the column that eventually gets forgotten in a
-- SUM somewhere. These are statement lines. `expenses` is what the owner spent.
-- The link between them is `expense_id`, and it is null far more often than not.
--
-- DISPOSITION IS THE POINT, not a status. The canvas's "Reads as" badge is not
-- one enum: a booked row reads as its category, an unbooked one reads as why it
-- was not booked. Keeping the reason is what lets the screen say thirty-three
-- rows were left uncategorised AND say what each of them was waiting for, which
-- is the difference between a number and a thing you can act on.
--
-- NOT STORED: the parser's `rate` rows. `RETAIL INTEREST RATE = 15.00%` is a
-- fact about the card, not a transaction, and it has nowhere to put an amount
-- or a merchant. It belongs on the account when the account learns to hold its
-- own terms, which is a different migration.
--
-- STILL EMPTY AFTER THIS: `card_statements.interest_charged` and `fees_charged`,
-- which the ingest hardcodes to 0 on every import. Typed charges need the parser
-- to recognise a charge line first, and it has no such rule — the only thing it
-- matches near interest is the RETAIL INTEREST RATE marker, which is a rate and
-- not an amount. Writing patterns for Maybank's charge wording without the
-- statement in front of you is how a wrong figure enters a finance app, so that
-- half waits for the PDF rather than for a table. See cards-canvas-gaps.md §3.

-- migrate:up

CREATE TABLE IF NOT EXISTS card_transactions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment_id  INTEGER NOT NULL REFERENCES commitments(id),
  -- Null when a line arrives without its header — the service allows importing
  -- rows against a card without a statement, and a row is still worth keeping.
  statement_id   INTEGER REFERENCES card_statements(id),

  -- BOTH DATES, which is half the reason this table exists. A card charge is
  -- transacted on one day and posted on another, the gap is the float the Cards
  -- screen explains, and `expenses` can only ever hold one of them.
  transacted_on  TEXT NOT NULL,
  posted_on      TEXT NOT NULL,

  description    TEXT NOT NULL,
  -- The statement's second column: where it happened, or nothing. Kept apart
  -- from the merchant rather than appended to it, because a merchant is what a
  -- rule matches on and a rule that has to skip past a city name is a rule that
  -- breaks when the same shop is visited in another one.
  location       TEXT NOT NULL DEFAULT '',
  amount         DOUBLE PRECISION NOT NULL,
  kind           TEXT NOT NULL,

  -- The foreign block, all three together or none of them. A converted amount
  -- with no rate cannot be checked and a rate with no amount says nothing, so
  -- the constraint below refuses a partial one rather than storing a figure
  -- nobody can reproduce.
  orig_currency  TEXT,
  orig_amount    DOUBLE PRECISION,
  fx_rate        DOUBLE PRECISION,

  -- An instalment line names its position in the plan. Null on every other kind.
  instalment_no  INTEGER,
  instalment_of  INTEGER,

  disposition    TEXT NOT NULL,
  -- Set only where the row became spending. The FK is what makes a booked row
  -- traceable back to the line that produced it.
  expense_id     INTEGER REFERENCES expenses(id),

  -- The same identity the expense booking already uses, so a re-import lands on
  -- the row it landed on last time instead of writing a second copy.
  ext_id         TEXT
);

ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_ext_id_key UNIQUE (ext_id);

ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_kind_check
  CHECK (kind IN ('retail','instalment','credit'));

-- booked      became an expenses row
-- commitment  matched a rule that names a commitment; counted there already
-- ignored     a rule said so, or the parser ruled it out as spending
-- unmatched   no rule; the only disposition that is asking a question
ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_disposition_check
  CHECK (disposition IN ('booked','commitment','ignored','unmatched'));

ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_dates_check
  CHECK (transacted_on ~ '^\d{4}-\d{2}-\d{2}$' AND posted_on ~ '^\d{4}-\d{2}-\d{2}$');

-- An expense exists exactly when the row was booked. Either half alone is a lie:
-- a booked row with no expense counts nothing, and an expense on an ignored row
-- is spending the screen promised not to log.
ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_booked_check
  CHECK ((disposition = 'booked') = (expense_id IS NOT NULL));

ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_foreign_check
  CHECK (num_nulls(orig_currency, orig_amount, fx_rate) IN (0, 3));

ALTER TABLE card_transactions ADD CONSTRAINT card_transactions_instalment_check
  CHECK (num_nulls(instalment_no, instalment_of) IN (0, 2));

-- The two questions this table is asked: everything on one statement, in the
-- order it happened, and everything on one card across statements.
CREATE INDEX IF NOT EXISTS card_transactions_statement_idx
  ON card_transactions (statement_id, transacted_on);
CREATE INDEX IF NOT EXISTS card_transactions_card_idx
  ON card_transactions (commitment_id, transacted_on);

-- migrate:down

DROP TABLE IF EXISTS card_transactions;
