-- The rate on the day the money landed, kept with the money.
--
-- money-redesign-plan.md 4(c), and the reason it waited: storing the pair was
-- always the easy half, and where a daily rate comes from was an open question in
-- 6. It is answered now — Bank Negara publishes one, free and unauthenticated,
-- and it is the same source a Malaysian tax filing would use.
--
-- WHY A DATED RATE AT ALL. Today the app holds ONE global fx_usd_myr, written by
-- the moomoo sync and applied to everything. A freelance invoice from March is
-- therefore converted at today's rate, which quietly restates history: the
-- twelve-month income chart changes shape every time the ringgit moves, and no
-- month on it is what actually arrived. A rate stored against the event fixes the
-- past in place, which is the only way a chart of the past can be true.
--
-- BOTH FIGURES ARE KEPT. income_events.gross stays in the source's own currency —
-- it is what the invoice said and it never changes. The rate sits beside it, so
-- the ringgit figure is derived rather than stored, and the conversion can always
-- be shown as the two numbers it came from rather than as one number nobody can
-- check.
--
-- fx_date IS NOT ALWAYS THE EVENT DATE, and that is why it is stored. Bank Negara
-- publishes on working days, so money that lands on a Saturday is converted at
-- Friday's rate. Recording which day the rate came from makes that visible
-- instead of silently attributing Friday's number to Saturday.
--
-- THE CACHE IS THE POINT OF THE TABLE. Rates never change once published, so a
-- date fetched once is a date fetched forever. It also means the app keeps working
-- when BNM is unreachable, for every date it has already seen — and a rate it has
-- never seen stays null rather than falling back to a wrong one silently. Nothing
-- here ever guesses a rate.

-- migrate:up

CREATE TABLE IF NOT EXISTS fx_rates (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base         text NOT NULL,
  quote        text NOT NULL DEFAULT 'MYR',
  date         text NOT NULL,
  -- The middle rate. Buying and selling are what a bank would give you; the
  -- middle is the published reference and the one a filing uses.
  rate         double precision NOT NULL,
  -- Some currencies are quoted per 100 units. Stored rather than assumed, so a
  -- future JPY or IDR row cannot be read as if it were per unit.
  unit         integer NOT NULL DEFAULT 1,
  source       text NOT NULL DEFAULT 'bnm',
  fetched_at   text NOT NULL DEFAULT to_char(CURRENT_DATE::timestamptz, 'YYYY-MM-DD'),
  CONSTRAINT fx_rates_rate_check CHECK (rate > 0),
  CONSTRAINT fx_rates_unit_check CHECK (unit > 0),
  CONSTRAINT fx_rates_date_check CHECK (date ~ '^\d{4}-\d{2}-\d{2}$')
);

-- One published rate per currency per day. Re-fetching a date corrects it rather
-- than leaving two rows for the reader to arbitrate between.
CREATE UNIQUE INDEX IF NOT EXISTS fx_rates_lookup_idx ON fx_rates (base, quote, date);

-- What this payment was actually converted at. Null on a MYR source, which is
-- most of them, and null on any foreign event recorded before this existed —
-- those keep falling back to the global rate, and the screen says which are which
-- rather than pretending the history was always dated.
ALTER TABLE income_events ADD COLUMN IF NOT EXISTS fx_rate double precision;
ALTER TABLE income_events ADD COLUMN IF NOT EXISTS fx_date text;

COMMENT ON COLUMN income_events.fx_rate IS
  'The rate this payment was converted at. Null means it falls back to the global rate — which restates history whenever the ringgit moves.';
COMMENT ON COLUMN income_events.fx_date IS
  'Which published day that rate is from. Not always the event date: BNM publishes on working days, so a Saturday payment carries Friday.';

ALTER TABLE income_events DROP CONSTRAINT IF EXISTS income_events_fx_check;
ALTER TABLE income_events ADD CONSTRAINT income_events_fx_check CHECK (
  (fx_rate IS NULL AND fx_date IS NULL)
  OR (fx_rate > 0 AND fx_date ~ '^\d{4}-\d{2}-\d{2}$')
);

-- migrate:down

ALTER TABLE income_events DROP CONSTRAINT IF EXISTS income_events_fx_check;
ALTER TABLE income_events DROP COLUMN IF EXISTS fx_date;
ALTER TABLE income_events DROP COLUMN IF EXISTS fx_rate;
DROP INDEX IF EXISTS fx_rates_lookup_idx;
DROP TABLE IF EXISTS fx_rates;
