-- What you owe and what leaves every month: loans, cards, rent, subscriptions.
--
-- Like `assets`, these are read by none of the broker code. A car instalment is
-- not a `cash_movements` row and must never reach cashBal(); a salary is not a
-- DIV transaction and must never reach income(). See commitments-and-income-plan.md.
--
-- THREE KINDS, because a car, a credit card and rent behave differently enough
-- that one shape would need a nullable column per difference anyway — and two of
-- those differences are load-bearing:
--
--   A loan payment is NOT an expense. It is part transfer: most of a car
--   instalment moves cash into equity and only the interest is spent. Rent spends
--   all of it. Treat them alike and you get cash flow right and net worth wrong.
--
--   A loan's whole future is derivable from five fields — principal, rate, rate
--   type, term, start — so this schema deliberately does NOT ask you to record 84
--   car payments. `commitment_payments` exists only for what a schedule cannot
--   know: an overpayment, a missed month, a settlement. An empty table means
--   everything went to plan, which is the common case and should cost no typing.
--   A revolving card is the opposite: nothing about it is derivable, so it keeps
--   a balance you update and a date saying when you last did.

-- migrate:up

CREATE TABLE IF NOT EXISTS commitments (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         TEXT NOT NULL,                    -- LOAN | REVOLVING | RECURRING
  name         TEXT NOT NULL,                    -- 'Myvi', 'House', 'Rent', 'CIMB Visa'
  lender       TEXT DEFAULT '',
  currency     TEXT NOT NULL DEFAULT 'MYR',
  due_day      INTEGER,                          -- 1..31; NULL for a card with no fixed date
  note         TEXT DEFAULT '',

  -- LOAN ------------------------------------------------------------------
  principal    DOUBLE PRECISION,                 -- the amount FINANCED, not the purchase price:
                                                 -- it includes any MRTA premium rolled into the
                                                 -- loan, on which you then pay interest for the
                                                 -- full term
  rate         DOUBLE PRECISION,                 -- annual, as a percentage, as the agreement quotes it
  rate_type    TEXT,                             -- FLAT | REDUCING — see below, this is load-bearing
  term_months  INTEGER,
  started_on   TEXT,                             -- YYYY-MM-DD, the first instalment
  instalment   DOUBLE PRECISION,                 -- the bank's own figure; overrides the derived one,
                                                 -- and since 1 Jul 2026 a rate change moves THIS
                                                 -- rather than the tenure, so it is not stable

  -- REVOLVING -------------------------------------------------------------
  credit_limit      DOUBLE PRECISION,
  balance           DOUBLE PRECISION,            -- a SNAPSHOT you update, never a derivation
  balance_as_of     TEXT,                        -- YYYY-MM-DD, so the screen can say how stale it is
  apr               DOUBLE PRECISION,            -- Malaysian cards are tiered 15/17/18 on payment
                                                 -- history, so this is per card and worth asking
  min_payment_pct   DOUBLE PRECISION DEFAULT 5,  -- 5% or a floor, whichever is higher — standardised
  min_payment_floor DOUBLE PRECISION DEFAULT 50, -- across every issuer checked

  -- RECURRING -------------------------------------------------------------
  amount       DOUBLE PRECISION,
  every_months INTEGER DEFAULT 1,                -- 1 monthly, 3 quarterly, 12 annual

  active       BOOLEAN NOT NULL DEFAULT true,
  ended_on     TEXT,
  sort_order   INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE commitments DROP CONSTRAINT IF EXISTS commitments_kind_check;
ALTER TABLE commitments ADD CONSTRAINT commitments_kind_check
  CHECK (kind IN ('LOAN','REVOLVING','RECURRING'));

-- FLAT      interest on the ORIGINAL principal for the whole term, no matter how
--           much has been repaid. Malaysian hire purchase, and personal financing
--           until BNM's prohibition bites on 1 January 2027. A 3.40% flat rate is
--           about 6.27% effective — roughly 1.8x — which is what makes comparing
--           it against a savings rate without converting so expensive.
-- REDUCING  interest on what is left. Mortgages, and anything BNM calls a "fixed
--           rate", which is NOT the same as flat however the marketing reads.
--
-- This cannot be inferred from the start date. The Hire-Purchase (Amendment) Act
-- 2026 abolished flat rate for NEW agreements from 1 June 2026 but grandfathered
-- existing ones, only some providers switched on day one, and the transition runs
-- to 31 March 2027 — so both regimes are being written at once. It comes off the
-- agreement, per loan.
ALTER TABLE commitments DROP CONSTRAINT IF EXISTS commitments_rate_type_check;
ALTER TABLE commitments ADD CONSTRAINT commitments_rate_type_check
  CHECK (rate_type IS NULL OR rate_type IN ('FLAT','REDUCING'));

-- Each kind must carry what its own math reads, so no commitment can exist in a
-- state the derivation cannot handle. The same guarantee goals_shape_check gives.
ALTER TABLE commitments DROP CONSTRAINT IF EXISTS commitments_shape_check;
ALTER TABLE commitments ADD CONSTRAINT commitments_shape_check CHECK (
     (kind = 'LOAN'      AND principal > 0 AND rate IS NOT NULL AND rate_type IS NOT NULL
                         AND term_months > 0 AND started_on IS NOT NULL)
  OR (kind = 'REVOLVING' AND apr IS NOT NULL)
  OR (kind = 'RECURRING' AND amount > 0 AND every_months > 0)
);

ALTER TABLE commitments DROP CONSTRAINT IF EXISTS commitments_due_day_check;
ALTER TABLE commitments ADD CONSTRAINT commitments_due_day_check
  CHECK (due_day IS NULL OR (due_day >= 1 AND due_day <= 31));

-- Deviations from the schedule, not the schedule itself. See the header.
CREATE TABLE IF NOT EXISTS commitment_payments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment_id   INTEGER NOT NULL REFERENCES commitments(id),
  date            TEXT NOT NULL,                 -- YYYY-MM-DD
  amount          DOUBLE PRECISION NOT NULL,     -- what actually left, always positive
  extra_principal DOUBLE PRECISION NOT NULL DEFAULT 0,  -- the part above the instalment, which
                                                        -- shortens the loan rather than prepaying it
  note            TEXT DEFAULT '',
  source          TEXT NOT NULL DEFAULT 'manual'
);

ALTER TABLE commitment_payments DROP CONSTRAINT IF EXISTS commitment_payments_amount_check;
ALTER TABLE commitment_payments ADD CONSTRAINT commitment_payments_amount_check
  CHECK (amount >= 0 AND extra_principal >= 0);

ALTER TABLE commitment_payments DROP CONSTRAINT IF EXISTS commitment_payments_date_check;
ALTER TABLE commitment_payments ADD CONSTRAINT commitment_payments_date_check
  CHECK (date ~ '^\d{4}-\d{2}-\d{2}$');

CREATE INDEX IF NOT EXISTS commitment_payments_lookup_idx
  ON commitment_payments (commitment_id, date DESC);

-- migrate:down

DROP INDEX IF EXISTS commitment_payments_lookup_idx;
DROP TABLE IF EXISTS commitment_payments;
DROP TABLE IF EXISTS commitments;
