-- What a merchant on a card statement actually is, decided once.
--
-- cards-plan.md §8 names three ways a statement importer would lie, and all three
-- are the same mistake wearing different clothes: guessing what a line means.
--
--   It would DOUBLE-COUNT the commitments. An electricity bill, a phone bill and
--   an insurance premium all appear on a card statement, and all three are already
--   RECURRING commitments subtracted from income on the Money screen. Booking them
--   as expenses too is the exact error expenses-plan.md drew its scope line to
--   prevent, arriving through a door that did not exist when the line was drawn.
--
--   It would book a CASH-OUT as spending. An EzyCash drawdown moves money into
--   your own account. Logging it would invent thousands of ringgit of living costs
--   that never happened.
--
--   It would GUESS A CATEGORY. Fuel and fast food are unambiguous; a payment
--   gateway is not — Maybank prints the aggregator, never the shop behind it. A
--   wrong category is worse than an empty one, because the group totals on the
--   spending screen are read as fact and nothing would ever flag them.
--
-- So the importer never decides. It applies rules the owner has already written,
-- and reports everything it could not match rather than filling it in. This table
-- is those rules.
--
-- THE MAP IS SMALL AND IT SHRINKS. On a real statement, 38 purchases were 22
-- distinct merchants and one of them was 16 of the rows. A decision made once
-- covers most of every statement after it, which is what makes the second import
-- almost free.
--
-- PATTERN, NOT MERCHANT ID. Statement descriptions are truncated, inconsistently
-- suffixed (`-EC`, `*E12`) and occasionally carry a reference number, so an exact
-- match would fail on the same shop next month. A prefix, matched
-- case-insensitively, survives that.

-- migrate:up

CREATE TABLE IF NOT EXISTS merchant_rules (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Matched as a case-insensitive PREFIX of the statement description.
  pattern       TEXT NOT NULL,
  action        TEXT NOT NULL,          -- EXPENSE | COMMITMENT | IGNORE
  category      TEXT,                   -- when EXPENSE; mirrors expenses_category_check
  commitment_id INTEGER REFERENCES commitments(id),   -- when COMMITMENT
  note          TEXT DEFAULT '',
  UNIQUE (pattern)
);

-- EXPENSE     it is spending; book it under `category`
-- COMMITMENT  it is already modelled as a RECURRING commitment; RECORD the match
--             and book nothing, or it counts twice against income
-- IGNORE      not spending at all — a cash-out, a payment, a plan instalment
ALTER TABLE merchant_rules DROP CONSTRAINT IF EXISTS merchant_rules_action_check;
ALTER TABLE merchant_rules ADD CONSTRAINT merchant_rules_action_check
  CHECK (action IN ('EXPENSE','COMMITMENT','IGNORE'));

-- Each action must carry what it needs to act, and nothing it does not. The same
-- guarantee commitments_shape_check gives, one table down.
ALTER TABLE merchant_rules DROP CONSTRAINT IF EXISTS merchant_rules_shape_check;
ALTER TABLE merchant_rules ADD CONSTRAINT merchant_rules_shape_check CHECK (
     (action = 'EXPENSE'    AND category IS NOT NULL AND commitment_id IS NULL)
  OR (action = 'COMMITMENT' AND commitment_id IS NOT NULL AND category IS NULL)
  OR (action = 'IGNORE'     AND category IS NULL AND commitment_id IS NULL)
);

ALTER TABLE merchant_rules DROP CONSTRAINT IF EXISTS merchant_rules_pattern_check;
ALTER TABLE merchant_rules ADD CONSTRAINT merchant_rules_pattern_check
  CHECK (length(trim(pattern)) >= 3);

-- Longest pattern first, so a specific rule beats a general one: `SHELL SELECT`
-- must win over `SHELL` if both exist.
CREATE INDEX IF NOT EXISTS merchant_rules_match_idx
  ON merchant_rules (length(pattern) DESC);

-- migrate:down

DROP INDEX IF EXISTS merchant_rules_match_idx;
DROP TABLE IF EXISTS merchant_rules;
