-- What arrives each month: salary, freelance, anything else.
--
-- Read by none of the broker code. A salary is NOT a `cash_movements` DEPOSIT and
-- must never reach cashBal(); it is not a DIV transaction and must never reach
-- income(), which means dividends and feeds the run rate — a month with a bonus
-- in it would otherwise read as a spectacular month for the ETFs.
--
-- THE TWO COLUMN GROUPS ON income_events ARE THE POINT OF THIS TABLE.
-- Employer EPF is not a deduction: it never passes through your pay, it is paid
-- alongside it. Netting it out of gross understates take-home; adding it to gross
-- overstates income. Separate groups mean neither mistake is available, and it is
-- what lets an employment event book the full contribution into the EPF asset
-- while subtracting only the employee's half from net.

-- migrate:up

CREATE TABLE IF NOT EXISTS income_sources (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind          TEXT NOT NULL,                  -- EMPLOYMENT | FREELANCE | RENTAL | OTHER
  name          TEXT NOT NULL,                  -- 'Day job', 'Design work'
  payer         TEXT DEFAULT '',                -- employer or client
  currency      TEXT NOT NULL DEFAULT 'MYR',
  cadence       TEXT NOT NULL DEFAULT 'MONTHLY',-- MONTHLY | IRREGULAR
  pay_day       INTEGER,                        -- 1..31, or -1 for the last working day
  gross_default DOUBLE PRECISION,               -- the expected gross, for forecasting a month
                                                -- that has not been recorded yet
  -- Where EPF contributions land. Nullable: a freelance source has none, and an
  -- employment source is perfectly usable before the EPF account is set up.
  epf_asset_id  INTEGER REFERENCES assets(id),

  active        BOOLEAN NOT NULL DEFAULT true,
  started_on    TEXT,
  ended_on      TEXT,
  sort_order    INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE income_sources DROP CONSTRAINT IF EXISTS income_sources_kind_check;
ALTER TABLE income_sources ADD CONSTRAINT income_sources_kind_check
  CHECK (kind IN ('EMPLOYMENT','FREELANCE','RENTAL','OTHER'));

-- A monthly source must say which day it lands, because the calendar and the
-- forecast both need one; an irregular source cannot have one, and storing a day
-- for it would invent a certainty the source does not have.
ALTER TABLE income_sources DROP CONSTRAINT IF EXISTS income_sources_shape_check;
ALTER TABLE income_sources ADD CONSTRAINT income_sources_shape_check CHECK (
     (cadence = 'MONTHLY'   AND pay_day IS NOT NULL AND (pay_day = -1 OR (pay_day >= 1 AND pay_day <= 31)))
  OR (cadence = 'IRREGULAR' AND pay_day IS NULL)
);

CREATE TABLE IF NOT EXISTS income_events (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id      INTEGER NOT NULL REFERENCES income_sources(id),
  date           TEXT NOT NULL,                 -- YYYY-MM-DD
  gross          DOUBLE PRECISION NOT NULL,

  -- DEDUCTED FROM the employee's pay.  net = gross - (all of these)
  epf_employee   DOUBLE PRECISION NOT NULL DEFAULT 0,
  socso_employee DOUBLE PRECISION NOT NULL DEFAULT 0,
  eis_employee   DOUBLE PRECISION NOT NULL DEFAULT 0,
  -- SKBBK / LINDUNG 24 JAM, live since 1 June 2026: 0.75% of wages, employee-borne
  -- with NO employer share, and enrolled by default since the opt-out window
  -- closed on 31 August 2026. Its own column because it must appear as its own
  -- payslip line and has no counterpart on the employer side.
  skbbk          DOUBLE PRECISION NOT NULL DEFAULT 0,
  pcb            DOUBLE PRECISION NOT NULL DEFAULT 0,
  zakat          DOUBLE PRECISION NOT NULL DEFAULT 0,
  other_deducted DOUBLE PRECISION NOT NULL DEFAULT 0,

  -- PAID ON TOP by the employer. NOT part of gross, NOT subtracted from net.
  epf_employer   DOUBLE PRECISION NOT NULL DEFAULT 0,
  socso_employer DOUBLE PRECISION NOT NULL DEFAULT 0,
  eis_employer   DOUBLE PRECISION NOT NULL DEFAULT 0,

  note           TEXT DEFAULT '',
  source         TEXT NOT NULL DEFAULT 'manual',
  ext_id         TEXT UNIQUE
);

ALTER TABLE income_events DROP CONSTRAINT IF EXISTS income_events_amounts_check;
ALTER TABLE income_events ADD CONSTRAINT income_events_amounts_check CHECK (
  gross >= 0 AND epf_employee >= 0 AND socso_employee >= 0 AND eis_employee >= 0
  AND skbbk >= 0 AND pcb >= 0 AND zakat >= 0 AND other_deducted >= 0
  AND epf_employer >= 0 AND socso_employer >= 0 AND eis_employer >= 0
);

ALTER TABLE income_events DROP CONSTRAINT IF EXISTS income_events_date_check;
ALTER TABLE income_events ADD CONSTRAINT income_events_date_check
  CHECK (date ~ '^\d{4}-\d{2}-\d{2}$');

CREATE INDEX IF NOT EXISTS income_events_lookup_idx ON income_events (source_id, date DESC);

-- migrate:down

DROP INDEX IF EXISTS income_events_lookup_idx;
DROP TABLE IF EXISTS income_events;
DROP TABLE IF EXISTS income_sources;
