-- The derivable part of a credit card: EPP, balance transfer, cash instalment.
--
-- 20260902020859 said a card keeps "a balance you update and a date saying when
-- you last did", because "nothing about a revolving balance is derivable". That
-- is still true, and this does not overturn it. What it says is that a card is
-- not ONLY a revolving balance. An instalment plan on the same card is derivable
-- in exactly the way a car loan is — a principal, a tenure, a start date and a
-- fixed instalment — and until now the only place to put one was to fold it into
-- the one number designed to be underivable.
--
-- WHAT THE FOLD COSTS. Bank Negara sets the minimum monthly repayment at 5% of
-- the balance with the instalments taken OUT, plus 100% of every contracted
-- instalment added back whole (BNM/RH/PD 028-141, 19 Dec 2025, para 13.1; the
-- arithmetic is published outright in issuers' own worked examples). cardMinimum()
-- implements the first limb against the whole balance and nothing else. On a card
-- carrying plans that is not merely wrong by a margin — it is wrong in a way no
-- percentage can fix, because one number cannot say which part is contracted and
-- which part is a floor you could clear tomorrow.
--
-- A LIST OF UNKNOWN LENGTH IS A TABLE. Three plans today, none next year, five
-- the year after. It cannot be columns, and it is not a free-standing LOAN either:
-- an instalment does not leave your wallet on its own (it is a line inside one
-- card payment, so a LOAN row would put a second mark on the calendar for a debit
-- that never happens separately), it consumes the card's limit, and the two rows
-- would have to be ended together by hand forever.
--
-- See cards-plan.md §2 and §4(b).

-- migrate:up

CREATE TABLE IF NOT EXISTS card_plans (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment_id  INTEGER NOT NULL REFERENCES commitments(id),
  kind           TEXT NOT NULL,               -- see the check below
  name           TEXT NOT NULL,               -- 'Fridge', 'Aircond', 'BT from CIMB'
  merchant       TEXT DEFAULT '',
  amount         DOUBLE PRECISION NOT NULL,   -- what was charged against the limit
  tenure_months  INTEGER NOT NULL,
  -- The BANK's figure, not a derivation. amount/tenure rarely divides evenly, the
  -- bank rounds and puts the remainder on the last month, and on a 0% plan the
  -- instalment simply IS the bank's number. Same call commitments.instalment
  -- already makes, for the same reason: a derived figure is wrong by sen every
  -- month forever, and sen accumulate into a balance that never quite settles.
  --
  -- It is the TOTAL billed monthly for this plan. Maybank bills EzyPay Plus as two
  -- lines — principal and its interest — and BNM's limb (b) counts both, so both
  -- belong in this one number. The split is recoverable from `rate` if ever needed.
  instalment     DOUBLE PRECISION NOT NULL,
  rate           DOUBLE PRECISION NOT NULL DEFAULT 0,   -- annual %, as quoted
  upfront_fee    DOUBLE PRECISION NOT NULL DEFAULT 0,   -- where the cost of "0%" hides
  -- Two dates because they are two different facts. A purchase on the 3rd, on a
  -- cycle closing on the 25th, has its first instalment on the October statement:
  -- the expense happened in September and the money starts moving in October.
  -- Collapsing them files the spending in the wrong month.
  purchased_on   TEXT NOT NULL,
  started_on     TEXT NOT NULL,
  settled_on     TEXT,                        -- early settlement; NULL while running
  -- A 0% plan can stop being one. Miss two consecutive minimum payments and the
  -- concession is retracted and the unbilled balance is billed at the retail rate
  -- (Hong Leong EPP cl 6; BSN terminates after three). That is a state transition,
  -- not a rate change, so liveness is not inferred from dates alone.
  status         TEXT NOT NULL DEFAULT 'ACTIVE',
  category       TEXT,                        -- the expense category, for the log
  note           TEXT DEFAULT '',
  source         TEXT NOT NULL DEFAULT 'manual'
);

-- EPP                      a merchant or converted-purchase instalment plan
-- BALANCE_TRANSFER         another issuer's balance, refinanced. NOT spending.
-- CASH_INSTALMENT          cash drawn against the line. NOT spending either.
-- AUTO_BALANCE_CONVERSION  new in the Dec 2025 PD (paras 14.1-14.2): a vulnerable
--                          cardholder's balance is converted to a 3-year term loan
--                          at not more than 13% p.a., whether or not they asked.
--                          It is the one kind that is never 0%, which is why `rate`
--                          is a column with a default rather than an assumption.
--                          The app RECORDS a conversion; it never evaluates the
--                          eligibility test and tells you that you qualify.
ALTER TABLE card_plans DROP CONSTRAINT IF EXISTS card_plans_kind_check;
ALTER TABLE card_plans ADD CONSTRAINT card_plans_kind_check
  CHECK (kind IN ('EPP','BALANCE_TRANSFER','CASH_INSTALMENT','AUTO_BALANCE_CONVERSION'));

ALTER TABLE card_plans DROP CONSTRAINT IF EXISTS card_plans_status_check;
ALTER TABLE card_plans ADD CONSTRAINT card_plans_status_check
  CHECK (status IN ('ACTIVE','RETRACTED','SETTLED'));

ALTER TABLE card_plans DROP CONSTRAINT IF EXISTS card_plans_amount_check;
ALTER TABLE card_plans ADD CONSTRAINT card_plans_amount_check
  CHECK (amount > 0 AND instalment > 0 AND tenure_months > 0
         AND rate >= 0 AND upfront_fee >= 0);

ALTER TABLE card_plans DROP CONSTRAINT IF EXISTS card_plans_dates_check;
ALTER TABLE card_plans ADD CONSTRAINT card_plans_dates_check
  CHECK (purchased_on ~ '^\d{4}-\d{2}-\d{2}$'
         AND started_on ~ '^\d{4}-\d{2}-\d{2}$'
         AND (settled_on IS NULL OR settled_on ~ '^\d{4}-\d{2}-\d{2}$'));

ALTER TABLE card_plans DROP CONSTRAINT IF EXISTS card_plans_source_check;
ALTER TABLE card_plans ADD CONSTRAINT card_plans_source_check
  CHECK (source IN ('manual','import'));

-- Read through the card, always. There is no screen that lists plans across cards.
CREATE INDEX IF NOT EXISTS card_plans_card_idx ON card_plans (commitment_id, started_on);

-- migrate:down

DROP INDEX IF EXISTS card_plans_card_idx;
DROP TABLE IF EXISTS card_plans;
