-- The bill, as a dated reading. One row a month per card account.
--
-- WHY THIS EXISTS, AND IT IS NOT "A NICER SCREEN". The spending residual in
-- 20260903050000 infers what living cost by assuming every ringgit spent leaves a
-- wallet inside the same window. A credit card is a device whose entire purpose is
-- to break that: money is spent in July and leaves in August. The correction needs
-- the float — the change in what the card owes over the same window — and a float
-- needs `owed` evaluated at TWO dates.
--
-- A single mutable `commitments.balance` can be read at one date only: today's.
-- That is the whole argument for this table. It comes from an arithmetic identity,
-- not from wanting more UI:
--
--   Δ(owed) = purchases + interest and fees − repayments
--   leftPocket = S + R,  float = P + C − R,  livingCost = S + P + C
--
-- The repayment cancels exactly, and no purchase is ever entered.
--
-- TWO DATED SOURCES FOR ONE NUMBER is normally what this app refuses. It is not
-- two here: they are the same kind of thing at different precisions. A statement is
-- a reading that also carries what the month cost and when it is due. owedOn()
-- takes whichever dated fact is latest at or before the date, across this table and
-- commitments.balance — the way wallet balance already reads across entries of
-- several sources. `balance` keeps working as the mid-cycle check; a statement
-- outranks it by being more recent, never by being special.
--
-- NOT A CHORE. One row a month per account, copied off a bill that arrives whether
-- this app exists or not — and sync/parse_maybank_statement.py reads it out of the
-- PDF, gated on three arithmetic checks the statement itself states.
--
-- See cards-plan.md §3, §4(c) and §8.

-- migrate:up

CREATE TABLE IF NOT EXISTS card_statements (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment_id    INTEGER NOT NULL REFERENCES commitments(id),
  statement_date   TEXT NOT NULL,              -- the day the cycle closed
  due_date         TEXT NOT NULL,
  closing_balance  DOUBLE PRECISION NOT NULL,  -- TOTAL owed as printed, plans included
  minimum_due      DOUBLE PRECISION,
  -- Kept apart for the reason principalPerMonth and interestPerMonth already are:
  -- one is the price of carrying a balance and can be driven to zero by paying in
  -- full, the other is the price of holding the card and cannot. A screen that
  -- totals them tells you to do the wrong thing.
  interest_charged DOUBLE PRECISION NOT NULL DEFAULT 0,
  fees_charged     DOUBLE PRECISION NOT NULL DEFAULT 0,
  note             TEXT DEFAULT '',
  source           TEXT NOT NULL DEFAULT 'manual',
  -- One statement per cycle. Re-importing the same PDF is then a no-op enforced by
  -- the database rather than by the importer remembering to check.
  UNIQUE (commitment_id, statement_date)
);

ALTER TABLE card_statements DROP CONSTRAINT IF EXISTS card_statements_dates_check;
ALTER TABLE card_statements ADD CONSTRAINT card_statements_dates_check
  CHECK (statement_date ~ '^\d{4}-\d{2}-\d{2}$' AND due_date ~ '^\d{4}-\d{2}-\d{2}$');

-- A closing balance of zero is a real statement — a card paid off and unused. A
-- negative one is a credit balance, which happens after a refund, so it is allowed
-- too. Only the charges are constrained.
ALTER TABLE card_statements DROP CONSTRAINT IF EXISTS card_statements_charges_check;
ALTER TABLE card_statements ADD CONSTRAINT card_statements_charges_check
  CHECK (interest_charged >= 0 AND fees_charged >= 0
         AND (minimum_due IS NULL OR minimum_due >= 0));

ALTER TABLE card_statements DROP CONSTRAINT IF EXISTS card_statements_source_check;
ALTER TABLE card_statements ADD CONSTRAINT card_statements_source_check
  CHECK (source IN ('manual','import'));

-- owedOn() walks backwards from a date, per card. This is that query.
CREATE INDEX IF NOT EXISTS card_statements_lookup_idx
  ON card_statements (commitment_id, statement_date DESC);

-- migrate:down

DROP INDEX IF EXISTS card_statements_lookup_idx;
DROP TABLE IF EXISTS card_statements;
