-- Holdings that are not in moomoo: ASB, Tabung Haji, EPF.
--
-- Deliberately NOT rows in `instruments`. Four things break if they go there, and
-- three break silently: cashBal() would subtract an ASB contribution from the
-- moomoo MYR wallet, monthlyIncomeRate() would average an annual distribution
-- into a 3-month run rate, Positions would render a row of dashes with a
-- permanent 0.00% P&L, and fund_metrics/fund_distributions are fed only by
-- moomoo's get_market_snapshot so they would never populate. These tables are
-- read by none of the broker code; the two worlds meet in one derived figure
-- (net worth) and nowhere else. See personal-assets-plan.md.
--
-- `kind` exists from the start but only SAVINGS is permitted today. COMMODITY
-- (gold: grams, a market price, a dealer spread) and ITEM (a house or car with a
-- manually-set value) are designed in the plan and cost nothing to add later —
-- the CHECK is the one line that changes. Shipping them now would mean columns
-- nothing can write and a price table nothing can fill.

-- migrate:up

CREATE TABLE IF NOT EXISTS assets (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         TEXT NOT NULL DEFAULT 'SAVINGS',
  name         TEXT NOT NULL,                    -- 'ASB', 'Tabung Haji', 'EPF'
  slug         TEXT NOT NULL UNIQUE,             -- 'asb' | 'tabung-haji' | 'epf' — stable UI key
  currency     TEXT NOT NULL DEFAULT 'MYR',
  institution  TEXT DEFAULT '',                  -- 'ASNB', 'Lembaga Tabung Haji', 'KWSP'
  account_ref  TEXT DEFAULT '',                  -- last 4 of the account number, for your own reference

  -- How the provider pays, and what it last paid. All display/estimate inputs:
  -- nothing here is load-bearing for a balance, which is derived from the ledger.
  unit_label   TEXT DEFAULT '',                  -- 'units' for ASB; '' for TH and EPF, which are just ringgit
  unit_cap     DOUBLE PRECISION,                 -- ASB's 300,000 — a progress bar, NEVER a validation:
                                                 -- reinvested distributions and inheritance can exceed it
  fiscal_year  TEXT NOT NULL DEFAULT '12-31',    -- MM-DD of the provider's year end. ASB and EPF are
                                                 -- December; ASB 2 and ASM are 31 March, ASB 3 is 30 June
  rate_basis   TEXT NOT NULL DEFAULT 'MIN_MONTHLY',  -- see below
  rate_quote   TEXT NOT NULL DEFAULT 'PERCENT',  -- PERCENT | SEN_PER_UNIT — display only
  last_rate    DOUBLE PRECISION,                 -- most recent declared base rate
  last_bonus   DOUBLE PRECISION,                 -- ASB's discretionary top-up, kept apart: it comes from
                                                 -- PNB rather than the fund, and an additional bonus when
                                                 -- declared applies only to the first 30,000 units

  sort_order   INTEGER NOT NULL DEFAULT 0,
  archived     BOOLEAN NOT NULL DEFAULT false,
  created_at   TEXT NOT NULL DEFAULT to_char(CURRENT_DATE,'YYYY-MM-DD')
);

ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_kind_check;
ALTER TABLE assets ADD CONSTRAINT assets_kind_check CHECK (kind IN ('SAVINGS'));

-- MIN_MONTHLY  the mean of the twelve monthly MINIMUM balances. ASNB: "Total
--              Monthly Minimum Balance for the Year / 12 Months x Income
--              Distribution Rate". Tabung Haji uses the same rule. Consequence:
--              a deposit never lifts the month it lands in, only the ones after.
-- MADB         EPF's modified aggregate daily balance — each month's contribution
--              earns from the last day of that month to 31 December, so January
--              money earns nearly a full year and December money almost none.
-- Same timing lesson, different arithmetic. This column is why that is a data
-- difference rather than a branch in the estimator.
ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_rate_basis_check;
ALTER TABLE assets ADD CONSTRAINT assets_rate_basis_check
  CHECK (rate_basis IN ('MIN_MONTHLY','MADB'));

ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_rate_quote_check;
ALTER TABLE assets ADD CONSTRAINT assets_rate_quote_check
  CHECK (rate_quote IN ('PERCENT','SEN_PER_UNIT'));

-- MM-DD, so the estimator can build the provider's own twelve-month window
-- rather than assuming the calendar year.
ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_fiscal_year_check;
ALTER TABLE assets ADD CONSTRAINT assets_fiscal_year_check
  CHECK (fiscal_year ~ '^\d{2}-\d{2}$');

-- Every movement. Balances are NEVER stored: they are re-derived from this
-- ledger on each render, the same invariant positions() and cashBal() run on.
--
-- There is no `units` column. For a SAVINGS asset units and ringgit are the same
-- number by definition (ASB is fixed at RM 1.00 per unit), and storing both
-- invites them to disagree — `unit_label` on the asset is what makes the UI say
-- "74,300 units" instead of "RM 74,300".
CREATE TABLE IF NOT EXISTS asset_entries (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id  INTEGER NOT NULL REFERENCES assets(id),
  type      TEXT NOT NULL,                       -- DEPOSIT | WITHDRAW | DISTRIBUTION | FEE
  date      TEXT NOT NULL,                       -- YYYY-MM-DD, as every other date column in this schema
  amount    DOUBLE PRECISION NOT NULL,           -- always positive; `type` carries the direction
  note      TEXT DEFAULT '',
  source    TEXT NOT NULL DEFAULT 'manual',      -- manual | payroll (an EPF contribution books itself)
  ext_id    TEXT UNIQUE                          -- the dedupe hook, for when something writes these for you
);

ALTER TABLE asset_entries DROP CONSTRAINT IF EXISTS asset_entries_type_check;
ALTER TABLE asset_entries ADD CONSTRAINT asset_entries_type_check
  CHECK (type IN ('DEPOSIT','WITHDRAW','DISTRIBUTION','FEE'));

-- Amount positive and `type` carrying the sign is how cash_movements already
-- works. Signed amounts PLUS a type column would be two sources of truth for
-- one fact, and they would eventually disagree.
ALTER TABLE asset_entries DROP CONSTRAINT IF EXISTS asset_entries_amount_check;
ALTER TABLE asset_entries ADD CONSTRAINT asset_entries_amount_check CHECK (amount >= 0);

ALTER TABLE asset_entries DROP CONSTRAINT IF EXISTS asset_entries_date_check;
ALTER TABLE asset_entries ADD CONSTRAINT asset_entries_date_check
  CHECK (date ~ '^\d{4}-\d{2}-\d{2}$');

-- The screen reads one asset's ledger newest-first.
CREATE INDEX IF NOT EXISTS asset_entries_lookup_idx ON asset_entries (asset_id, date DESC);

-- migrate:down

DROP INDEX IF EXISTS asset_entries_lookup_idx;
DROP TABLE IF EXISTS asset_entries;
DROP TABLE IF EXISTS assets;
