-- Baseline: the schema as it existed before migrations were introduced.
--
-- Written with IF NOT EXISTS so it is a no-op against a database that already
-- has these tables — that is what lets an existing install adopt dbmate without
-- rebuilding. On a fresh database it creates everything.
--
-- Every change from here on gets its own migration. Do not edit this file.

-- migrate:up

-- Dates the UI renders (trade_date, cash date, snapshot date) stay TEXT
-- 'YYYY-MM-DD': the frontend parses them as strings. Internal timestamps use
-- native types.

CREATE TABLE IF NOT EXISTS instruments (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker        TEXT NOT NULL UNIQUE,       -- how YOU call it, e.g. ETCO, AAPL
  name          TEXT DEFAULT '',
  market        TEXT NOT NULL,              -- MY | US
  currency      TEXT NOT NULL,              -- MYR | USD
  yahoo_symbol  TEXT DEFAULT '',            -- e.g. 5279.KL for Bursa, AAPL for US
  moomoo_code   TEXT DEFAULT ''             -- moomoo code e.g. MY.5279, US.AAPL (for sync matching)
);

-- ext_id carries the moomoo deal id. Its UNIQUE constraint is what makes
-- re-running the sync a no-op instead of duplicating every fill.
CREATE TABLE IF NOT EXISTS transactions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id INTEGER NOT NULL REFERENCES instruments(id),
  side          TEXT NOT NULL CHECK (side IN ('BUY','SELL','DIV')),
  qty           DOUBLE PRECISION NOT NULL DEFAULT 0,
  price         DOUBLE PRECISION NOT NULL DEFAULT 0,
  fees          DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount        DOUBLE PRECISION DEFAULT NULL,   -- used for DIV
  trade_date    TEXT NOT NULL,                   -- YYYY-MM-DD
  source        TEXT NOT NULL DEFAULT 'manual',  -- manual | api | csv
  ext_id        TEXT UNIQUE                      -- moomoo deal id → dedupe on re-sync
);

CREATE TABLE IF NOT EXISTS cash_movements (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type     TEXT NOT NULL CHECK (type IN ('DEPOSIT','WITHDRAW','DIVIDEND','FEE')),
  currency TEXT NOT NULL,
  amount   DOUBLE PRECISION NOT NULL,
  date     TEXT NOT NULL,
  source   TEXT NOT NULL DEFAULT 'manual',
  ext_id   TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS prices (
  instrument_id INTEGER PRIMARY KEY REFERENCES instruments(id),
  price         DOUBLE PRECISION NOT NULL,
  fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  source        TEXT NOT NULL DEFAULT 'manual'   -- manual | yahoo | moomoo
);

CREATE TABLE IF NOT EXISTS goals (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_id  INTEGER NOT NULL REFERENCES instruments(id),
  target_qty     DOUBLE PRECISION NOT NULL,
  monthly_budget DOUBLE PRECISION DEFAULT NULL,  -- in RM
  created_at     TEXT NOT NULL DEFAULT to_char(CURRENT_DATE,'YYYY-MM-DD')
);

CREATE TABLE IF NOT EXISTS snapshots (
  date     TEXT PRIMARY KEY,                     -- YYYY-MM-DD
  value_rm DOUBLE PRECISION NOT NULL,            -- invested value, RM-combined
  cash_rm  DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- fx is overwritten by the sync worker with the rate moomoo itself is using.
INSERT INTO settings (key, value) VALUES ('fx_usd_myr','4.22'), ('last_sync','')
  ON CONFLICT (key) DO NOTHING;

-- migrate:down

DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS cash_movements;
DROP TABLE IF EXISTS snapshots;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS instruments;
