-- What you actually spent, by category.
--
-- THIS REVERSES §2 OF commitments-and-income-plan.md, deliberately and on the
-- owner's instruction. That section argues an app which asks you to enter
-- groceries is abandoned in three weeks, and the argument is sound — it is not
-- wrong here, it is accepted and answered.
--
-- The answer is that this app can already tell when the log has gone stale.
-- spendingFor() infers what actually left the wallets from readings, without
-- anything being entered. Logging expenses does NOT replace that figure; it is
-- reconciled against it. Logged RM 1,200 against an inferred RM 1,797 means the
-- log is 67% complete, and the app says so. An abandoned expense log that
-- silently under-reports is the failure §2 feared; one that reports its own
-- incompleteness is a different thing.
--
-- SCOPE: unpredictable spending only. Rent, insurance, phone and subscriptions
-- are RECURRING commitments and belong there — they are known in advance, they
-- are already modelled, and entering them twice would double-count them against
-- income. The categories below are deliberately the ones a commitment cannot be.
--
-- NOT A BANK FEED. Every row is typed by hand, because Malaysia has no
-- open-banking mandate to import from. `source` exists so that an importer added
-- later can be told apart from manual entry without a schema change, exactly as
-- asset_entries.source does.

-- migrate:up

CREATE TABLE IF NOT EXISTS expenses (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date      TEXT NOT NULL,                    -- YYYY-MM-DD, as every other date column
  amount    DOUBLE PRECISION NOT NULL,        -- always positive; an expense has one direction
  currency  TEXT NOT NULL DEFAULT 'MYR',
  category  TEXT NOT NULL,
  note      TEXT DEFAULT '',
  -- Which wallet it came out of, when known. Optional because the log is useful
  -- before the wallets are set up, and because cash has no account. When it IS
  -- set, a per-wallet reconciliation becomes possible — the owner spends from
  -- several cards by purpose, so that split is real rather than hypothetical.
  asset_id  INTEGER REFERENCES assets(id),
  source    TEXT NOT NULL DEFAULT 'manual',   -- manual | import
  ext_id    TEXT UNIQUE                       -- the dedupe hook, for an importer later
);

-- A fixed list rather than free text. Free text fragments on typos — "petrol",
-- "Petrol", "fuel" become three categories and every total is wrong in a way
-- nothing surfaces. The set is short on purpose: a category nobody uses is a
-- decision nobody wanted to make at the point of entry, and the point of entry
-- is where this feature is won or lost.
--
-- Chosen for what they are NOT: none of these can be a RECURRING commitment.
ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_category_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_category_check
  CHECK (category IN (
    'GROCERIES',   -- the weekly shop
    'EATING_OUT',  -- restaurants, kopitiam, delivery
    'TRANSPORT',   -- Grab, tolls, parking, public transport
    'FUEL',        -- petrol, charging
    'HEALTH',      -- clinic, pharmacy, dental
    'SHOPPING',    -- clothes, household, anything bought once
    'FAMILY',      -- money given to parents or relatives
    'CHARITY',     -- sedekah, donations
    'OTHER'
  ));

-- Zero is not an expense, and a negative one is a refund wearing the wrong sign.
-- A refund belongs as its own concept or not at all; it is not modelled here.
ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_amount_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_amount_check CHECK (amount > 0);

ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_date_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_date_check
  CHECK (date ~ '^\d{4}-\d{2}-\d{2}$');

ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_source_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_source_check
  CHECK (source IN ('manual','import'));

-- The screen reads a month at a time, newest first.
CREATE INDEX IF NOT EXISTS expenses_date_idx ON expenses (date DESC);

-- migrate:down

DROP INDEX IF EXISTS expenses_date_idx;
DROP TABLE IF EXISTS expenses;
