--
-- PostgreSQL database dump
--

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg11+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asset_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset_entries (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    type text NOT NULL,
    date text NOT NULL,
    amount double precision NOT NULL,
    note text DEFAULT ''::text,
    source text DEFAULT 'manual'::text NOT NULL,
    ext_id text,
    CONSTRAINT asset_entries_amount_check CHECK ((amount >= (0)::double precision)),
    CONSTRAINT asset_entries_date_check CHECK ((date ~ '^\d{4}-\d{2}-\d{2}$'::text)),
    CONSTRAINT asset_entries_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'payroll'::text, 'opening'::text]))),
    CONSTRAINT asset_entries_type_check CHECK ((type = ANY (ARRAY['DEPOSIT'::text, 'WITHDRAW'::text, 'DISTRIBUTION'::text, 'FEE'::text, 'BALANCE'::text])))
);


--
-- Name: asset_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets (
    id integer NOT NULL,
    kind text DEFAULT 'SAVINGS'::text NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    currency text DEFAULT 'MYR'::text NOT NULL,
    institution text DEFAULT ''::text,
    account_ref text DEFAULT ''::text,
    unit_label text DEFAULT ''::text,
    unit_cap double precision,
    fiscal_year text DEFAULT '12-31'::text NOT NULL,
    rate_basis text DEFAULT 'MIN_MONTHLY'::text NOT NULL,
    rate_quote text DEFAULT 'PERCENT'::text NOT NULL,
    last_rate double precision,
    last_bonus double precision,
    sort_order integer DEFAULT 0 NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    created_at text DEFAULT to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY-MM-DD'::text) NOT NULL,
    product_id text,
    liquidity text DEFAULT 'SAVINGS'::text NOT NULL,
    CONSTRAINT assets_fiscal_year_check CHECK ((fiscal_year ~ '^\d{2}-\d{2}$'::text)),
    CONSTRAINT assets_illiquid_is_item_check CHECK (((liquidity <> 'ILLIQUID'::text) OR (kind = 'ITEM'::text))),
    CONSTRAINT assets_item_shape_check CHECK (((kind <> 'ITEM'::text) OR ((liquidity = 'ILLIQUID'::text) AND (rate_basis = 'NONE'::text) AND (unit_cap IS NULL)))),
    CONSTRAINT assets_kind_check CHECK ((kind = ANY (ARRAY['SAVINGS'::text, 'ITEM'::text]))),
    CONSTRAINT assets_liquidity_check CHECK ((liquidity = ANY (ARRAY['WALLET'::text, 'SAVINGS'::text, 'LOCKED'::text, 'ILLIQUID'::text]))),
    CONSTRAINT assets_rate_basis_check CHECK ((rate_basis = ANY (ARRAY['MIN_MONTHLY'::text, 'MADB'::text, 'NONE'::text]))),
    CONSTRAINT assets_rate_quote_check CHECK ((rate_quote = ANY (ARRAY['PERCENT'::text, 'SEN_PER_UNIT'::text])))
);


--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: broker_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.broker_positions (
    instrument_id integer NOT NULL,
    qty double precision NOT NULL,
    avg_cost double precision DEFAULT 0 NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT broker_positions_qty_check CHECK (((qty >= (0)::double precision) AND (avg_cost >= (0)::double precision)))
);


--
-- Name: card_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_plans (
    id integer NOT NULL,
    commitment_id integer NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    merchant text DEFAULT ''::text,
    amount double precision NOT NULL,
    tenure_months integer NOT NULL,
    instalment double precision NOT NULL,
    rate double precision DEFAULT 0 NOT NULL,
    upfront_fee double precision DEFAULT 0 NOT NULL,
    purchased_on text NOT NULL,
    started_on text NOT NULL,
    settled_on text,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    category text,
    note text DEFAULT ''::text,
    source text DEFAULT 'manual'::text NOT NULL,
    CONSTRAINT card_plans_amount_check CHECK (((amount > (0)::double precision) AND (instalment > (0)::double precision) AND (tenure_months > 0) AND (rate >= (0)::double precision) AND (upfront_fee >= (0)::double precision))),
    CONSTRAINT card_plans_dates_check CHECK (((purchased_on ~ '^\d{4}-\d{2}-\d{2}$'::text) AND (started_on ~ '^\d{4}-\d{2}-\d{2}$'::text) AND ((settled_on IS NULL) OR (settled_on ~ '^\d{4}-\d{2}-\d{2}$'::text)))),
    CONSTRAINT card_plans_kind_check CHECK ((kind = ANY (ARRAY['EPP'::text, 'BALANCE_TRANSFER'::text, 'CASH_INSTALMENT'::text, 'AUTO_BALANCE_CONVERSION'::text]))),
    CONSTRAINT card_plans_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'import'::text]))),
    CONSTRAINT card_plans_status_check CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'RETRACTED'::text, 'SETTLED'::text])))
);


--
-- Name: card_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_statements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_statements (
    id integer NOT NULL,
    commitment_id integer NOT NULL,
    statement_date text NOT NULL,
    due_date text NOT NULL,
    closing_balance double precision NOT NULL,
    minimum_due double precision,
    interest_charged double precision DEFAULT 0 NOT NULL,
    fees_charged double precision DEFAULT 0 NOT NULL,
    note text DEFAULT ''::text,
    source text DEFAULT 'manual'::text NOT NULL,
    CONSTRAINT card_statements_charges_check CHECK (((interest_charged >= (0)::double precision) AND (fees_charged >= (0)::double precision) AND ((minimum_due IS NULL) OR (minimum_due >= (0)::double precision)))),
    CONSTRAINT card_statements_dates_check CHECK (((statement_date ~ '^\d{4}-\d{2}-\d{2}$'::text) AND (due_date ~ '^\d{4}-\d{2}-\d{2}$'::text))),
    CONSTRAINT card_statements_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'import'::text])))
);


--
-- Name: card_statements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_statements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_statements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_transactions (
    id integer NOT NULL,
    commitment_id integer NOT NULL,
    statement_id integer,
    transacted_on text NOT NULL,
    posted_on text NOT NULL,
    description text NOT NULL,
    location text DEFAULT ''::text NOT NULL,
    amount double precision NOT NULL,
    kind text NOT NULL,
    orig_currency text,
    orig_amount double precision,
    fx_rate double precision,
    instalment_no integer,
    instalment_of integer,
    disposition text NOT NULL,
    expense_id integer,
    ext_id text,
    CONSTRAINT card_transactions_booked_check CHECK (((disposition = 'booked'::text) = (expense_id IS NOT NULL))),
    CONSTRAINT card_transactions_dates_check CHECK (((transacted_on ~ '^\d{4}-\d{2}-\d{2}$'::text) AND (posted_on ~ '^\d{4}-\d{2}-\d{2}$'::text))),
    CONSTRAINT card_transactions_disposition_check CHECK ((disposition = ANY (ARRAY['booked'::text, 'commitment'::text, 'ignored'::text, 'unmatched'::text]))),
    CONSTRAINT card_transactions_foreign_check CHECK ((num_nulls(orig_currency, orig_amount, fx_rate) = ANY (ARRAY[0, 3]))),
    CONSTRAINT card_transactions_instalment_check CHECK ((num_nulls(instalment_no, instalment_of) = ANY (ARRAY[0, 2]))),
    CONSTRAINT card_transactions_kind_check CHECK ((kind = ANY (ARRAY['retail'::text, 'instalment'::text, 'credit'::text])))
);


--
-- Name: card_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cash_movements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cash_movements (
    id integer NOT NULL,
    type text NOT NULL,
    currency text NOT NULL,
    amount double precision NOT NULL,
    date text NOT NULL,
    source text DEFAULT 'manual'::text NOT NULL,
    ext_id text,
    instrument_id integer,
    CONSTRAINT cash_movements_type_check CHECK ((type = ANY (ARRAY['DEPOSIT'::text, 'WITHDRAW'::text, 'DIVIDEND'::text, 'FEE'::text])))
);


--
-- Name: cash_movements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cash_movements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_movements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commitment_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commitment_payments (
    id integer NOT NULL,
    commitment_id integer NOT NULL,
    date text NOT NULL,
    amount double precision NOT NULL,
    extra_principal double precision DEFAULT 0 NOT NULL,
    note text DEFAULT ''::text,
    source text DEFAULT 'manual'::text NOT NULL,
    CONSTRAINT commitment_payments_amount_check CHECK (((amount >= (0)::double precision) AND (extra_principal >= (0)::double precision))),
    CONSTRAINT commitment_payments_date_check CHECK ((date ~ '^\d{4}-\d{2}-\d{2}$'::text))
);


--
-- Name: commitment_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commitment_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commitment_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commitments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commitments (
    id integer NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    lender text DEFAULT ''::text,
    currency text DEFAULT 'MYR'::text NOT NULL,
    due_day integer,
    note text DEFAULT ''::text,
    principal double precision,
    rate double precision,
    rate_type text,
    term_months integer,
    started_on text,
    instalment double precision,
    credit_limit double precision,
    balance double precision,
    balance_as_of text,
    apr double precision,
    min_payment_pct double precision DEFAULT 5,
    min_payment_floor double precision DEFAULT 50,
    card_count integer,
    amount double precision,
    every_months integer DEFAULT 1,
    active boolean DEFAULT true NOT NULL,
    ended_on text,
    sort_order integer DEFAULT 0 NOT NULL,
    statement_day integer,
    limit_release text,
    asset_id integer,
    collected_by_id integer,
    CONSTRAINT commitments_asset_is_loan_check CHECK (((asset_id IS NULL) OR (kind = 'LOAN'::text))),
    CONSTRAINT commitments_card_count_check CHECK (((card_count IS NULL) OR ((kind = 'REVOLVING'::text) AND ((card_count >= 1) AND (card_count <= 20))))),
    CONSTRAINT commitments_collected_is_recurring_check CHECK (((collected_by_id IS NULL) OR (kind = 'RECURRING'::text))),
    CONSTRAINT commitments_collected_not_self_check CHECK (((collected_by_id IS NULL) OR (collected_by_id <> id))),
    CONSTRAINT commitments_due_day_check CHECK (((due_day IS NULL) OR ((due_day >= 1) AND (due_day <= 31)))),
    CONSTRAINT commitments_kind_check CHECK ((kind = ANY (ARRAY['LOAN'::text, 'REVOLVING'::text, 'RECURRING'::text]))),
    CONSTRAINT commitments_limit_release_check CHECK (((limit_release IS NULL) OR (limit_release = ANY (ARRAY['PROGRESSIVE'::text, 'ON_SETTLEMENT'::text])))),
    CONSTRAINT commitments_rate_type_check CHECK (((rate_type IS NULL) OR (rate_type = ANY (ARRAY['FLAT'::text, 'REDUCING'::text])))),
    CONSTRAINT commitments_shape_check CHECK ((((kind = 'LOAN'::text) AND ((COALESCE(principal, (0)::double precision) > (0)::double precision) OR (COALESCE(instalment, (0)::double precision) > (0)::double precision)) AND ((principal IS NULL) OR (principal > (0)::double precision)) AND ((instalment IS NULL) OR (instalment > (0)::double precision)) AND (((rate IS NULL) AND (rate_type IS NULL)) OR ((rate IS NOT NULL) AND (rate_type IS NOT NULL))) AND ((rate IS NOT NULL) OR (COALESCE(instalment, (0)::double precision) > (0)::double precision)) AND (term_months > 0) AND (started_on IS NOT NULL)) OR ((kind = 'REVOLVING'::text) AND (apr IS NOT NULL)) OR ((kind = 'RECURRING'::text) AND (amount > (0)::double precision) AND (every_months > 0)))),
    CONSTRAINT commitments_statement_day_check CHECK (((statement_day IS NULL) OR ((statement_day >= 1) AND (statement_day <= 31))))
);


--
-- Name: COLUMN commitments.credit_limit; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.commitments.credit_limit IS 'Belongs to the ACCOUNT, not the card. Two cards can share one limit, one due date and one minimum.';


--
-- Name: COLUMN commitments.min_payment_floor; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.commitments.min_payment_floor IS 'Issuer practice, not regulation. BSN 50, Maybank 25. BNM 13.1 mandates no floor.';


--
-- Name: COLUMN commitments.asset_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.commitments.asset_id IS 'What this loan bought, if it is tracked. Nullable on purpose: a loan with nothing linked counts only the debt, and the Loans screen says so.';


--
-- Name: COLUMN commitments.collected_by_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.commitments.collected_by_id IS 'The REVOLVING account that collects this recurring charge, if a card does. Adds no money to the month — the charge is still counted once, on Commitments. It says which day the money actually leaves.';
--
-- Name: COLUMN commitments.card_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.commitments.card_count IS 'Pieces of plastic sharing this limit. NULL means never asked, never 1 by default.';


--
-- Name: commitments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commitments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commitments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: declared_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.declared_rates (
    id integer NOT NULL,
    institution_id text NOT NULL,
    product_id text NOT NULL,
    year integer NOT NULL,
    rate double precision NOT NULL,
    bonus double precision,
    shariah double precision,
    note text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT declared_rates_rate_check CHECK (((rate >= (0)::double precision) AND ((bonus IS NULL) OR (bonus >= (0)::double precision)) AND ((shariah IS NULL) OR (shariah >= (0)::double precision)))),
    CONSTRAINT declared_rates_sane_check CHECK (((rate <= (100)::double precision) AND ((bonus IS NULL) OR (bonus <= (100)::double precision)) AND ((shariah IS NULL) OR (shariah <= (100)::double precision)))),
    CONSTRAINT declared_rates_year_check CHECK (((year >= 1990) AND (year <= 2200)))
);


--
-- Name: declared_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.declared_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.declared_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    id integer NOT NULL,
    date text NOT NULL,
    amount double precision NOT NULL,
    currency text DEFAULT 'MYR'::text NOT NULL,
    category text NOT NULL,
    note text DEFAULT ''::text,
    asset_id integer,
    source text DEFAULT 'manual'::text NOT NULL,
    ext_id text,
    CONSTRAINT expenses_amount_check CHECK ((amount > (0)::double precision)),
    CONSTRAINT expenses_category_check CHECK ((category = ANY (ARRAY['GROCERIES'::text, 'MEALS_OUT'::text, 'COFFEE_SNACKS'::text, 'FUEL'::text, 'FARES'::text, 'PARKING_TOLLS'::text, 'HOUSEHOLD_GOODS'::text, 'HOME_UPKEEP'::text, 'MEDICAL'::text, 'PHARMACY'::text, 'GROOMING'::text, 'TOILETRIES'::text, 'CLOTHES'::text, 'THINGS'::text, 'GOING_OUT'::text, 'GAMES_MEDIA'::text, 'FLIGHTS_STAYS'::text, 'TRIP_SPENDING'::text, 'RELATIVES'::text, 'KIDS'::text, 'PETS'::text, 'GIFTS'::text, 'DONATIONS'::text, 'COURSES'::text, 'BOOKS'::text, 'BANK_FEES'::text, 'CARD_CHARGES'::text, 'UNCATEGORISED'::text]))),
    CONSTRAINT expenses_date_check CHECK ((date ~ '^\d{4}-\d{2}-\d{2}$'::text)),
    CONSTRAINT expenses_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'import'::text])))
);


--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_distributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_distributions (
    instrument_id integer NOT NULL,
    ex_date text NOT NULL,
    per_share double precision NOT NULL
);


--
-- Name: fund_metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_metrics (
    instrument_id integer NOT NULL,
    aum double precision,
    nav double precision,
    outstanding_units double precision,
    dividend_yield double precision,
    premium double precision,
    asset_class text,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: fx_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fx_rates (
    id integer NOT NULL,
    base text NOT NULL,
    quote text DEFAULT 'MYR'::text NOT NULL,
    date text NOT NULL,
    rate double precision NOT NULL,
    unit integer DEFAULT 1 NOT NULL,
    source text DEFAULT 'bnm'::text NOT NULL,
    fetched_at text DEFAULT to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY-MM-DD'::text) NOT NULL,
    CONSTRAINT fx_rates_date_check CHECK ((date ~ '^\d{4}-\d{2}-\d{2}$'::text)),
    CONSTRAINT fx_rates_rate_check CHECK ((rate > (0)::double precision)),
    CONSTRAINT fx_rates_unit_check CHECK ((unit > 0))
);


--
-- Name: fx_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fx_rates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fx_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id integer NOT NULL,
    instrument_id integer,
    target_qty double precision DEFAULT 0 NOT NULL,
    monthly_budget double precision,
    created_at text DEFAULT to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY-MM-DD'::text) NOT NULL,
    kind text DEFAULT 'SHARES'::text NOT NULL,
    target_amount double precision,
    asset_id integer,
    CONSTRAINT goals_kind_check CHECK ((kind = ANY (ARRAY['SHARES'::text, 'INCOME_TOTAL'::text, 'INCOME_MONTHLY'::text, 'INCOME_YEAR'::text, 'INCOME_PER_PAYMENT'::text, 'ASSET_BALANCE'::text]))),
    CONSTRAINT goals_shape_check CHECK ((((kind = 'SHARES'::text) AND (instrument_id IS NOT NULL) AND (target_qty > (0)::double precision) AND (asset_id IS NULL)) OR ((kind = 'INCOME_PER_PAYMENT'::text) AND (instrument_id IS NOT NULL) AND (target_amount > (0)::double precision) AND (asset_id IS NULL)) OR ((kind = ANY (ARRAY['INCOME_TOTAL'::text, 'INCOME_MONTHLY'::text, 'INCOME_YEAR'::text])) AND (target_amount > (0)::double precision) AND (asset_id IS NULL)) OR ((kind = 'ASSET_BALANCE'::text) AND (asset_id IS NOT NULL) AND (target_amount > (0)::double precision) AND (instrument_id IS NULL))))
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: income_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.income_events (
    id integer NOT NULL,
    source_id integer NOT NULL,
    date text NOT NULL,
    gross double precision NOT NULL,
    epf_employee double precision DEFAULT 0 NOT NULL,
    socso_employee double precision DEFAULT 0 NOT NULL,
    eis_employee double precision DEFAULT 0 NOT NULL,
    skbbk double precision DEFAULT 0 NOT NULL,
    pcb double precision DEFAULT 0 NOT NULL,
    zakat double precision DEFAULT 0 NOT NULL,
    other_deducted double precision DEFAULT 0 NOT NULL,
    epf_employer double precision DEFAULT 0 NOT NULL,
    socso_employer double precision DEFAULT 0 NOT NULL,
    eis_employer double precision DEFAULT 0 NOT NULL,
    note text DEFAULT ''::text,
    source text DEFAULT 'manual'::text NOT NULL,
    ext_id text,
    fx_rate double precision,
    fx_date text,
    CONSTRAINT income_events_amounts_check CHECK (((gross >= (0)::double precision) AND (epf_employee >= (0)::double precision) AND (socso_employee >= (0)::double precision) AND (eis_employee >= (0)::double precision) AND (skbbk >= (0)::double precision) AND (pcb >= (0)::double precision) AND (zakat >= (0)::double precision) AND (other_deducted >= (0)::double precision) AND (epf_employer >= (0)::double precision) AND (socso_employer >= (0)::double precision) AND (eis_employer >= (0)::double precision))),
    CONSTRAINT income_events_date_check CHECK ((date ~ '^\d{4}-\d{2}-\d{2}$'::text)),
    CONSTRAINT income_events_fx_check CHECK ((((fx_rate IS NULL) AND (fx_date IS NULL)) OR ((fx_rate > (0)::double precision) AND (fx_date ~ '^\d{4}-\d{2}-\d{2}$'::text))))
);


--
-- Name: COLUMN income_events.fx_rate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.income_events.fx_rate IS 'The rate this payment was converted at. Null means it falls back to the global rate — which restates history whenever the ringgit moves.';


--
-- Name: COLUMN income_events.fx_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.income_events.fx_date IS 'Which published day that rate is from. Not always the event date: BNM publishes on working days, so a Saturday payment carries Friday.';


--
-- Name: income_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.income_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.income_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: income_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.income_sources (
    id integer NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    payer text DEFAULT ''::text,
    currency text DEFAULT 'MYR'::text NOT NULL,
    cadence text DEFAULT 'MONTHLY'::text NOT NULL,
    pay_day integer,
    gross_default double precision,
    active boolean DEFAULT true NOT NULL,
    started_on text,
    ended_on text,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT income_sources_kind_check CHECK ((kind = ANY (ARRAY['EMPLOYMENT'::text, 'FREELANCE'::text, 'RENTAL'::text, 'OTHER'::text]))),
    CONSTRAINT income_sources_shape_check CHECK ((((cadence = 'MONTHLY'::text) AND (pay_day IS NOT NULL) AND ((pay_day = '-1'::integer) OR ((pay_day >= 1) AND (pay_day <= 31)))) OR ((cadence = 'IRREGULAR'::text) AND (pay_day IS NULL))))
);


--
-- Name: income_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.income_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.income_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instruments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instruments (
    id integer NOT NULL,
    ticker text NOT NULL,
    name text DEFAULT ''::text,
    market text NOT NULL,
    currency text NOT NULL,
    yahoo_symbol text DEFAULT ''::text,
    moomoo_code text DEFAULT ''::text
);


--
-- Name: instruments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.instruments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.instruments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: merchant_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.merchant_rules (
    id integer NOT NULL,
    pattern text NOT NULL,
    action text NOT NULL,
    category text,
    commitment_id integer,
    note text DEFAULT ''::text,
    CONSTRAINT merchant_rules_action_check CHECK ((action = ANY (ARRAY['EXPENSE'::text, 'COMMITMENT'::text, 'IGNORE'::text]))),
    CONSTRAINT merchant_rules_pattern_check CHECK ((length(TRIM(BOTH FROM pattern)) >= 3)),
    CONSTRAINT merchant_rules_shape_check CHECK ((((action = 'EXPENSE'::text) AND (category IS NOT NULL) AND (commitment_id IS NULL)) OR ((action = 'COMMITMENT'::text) AND (commitment_id IS NOT NULL) AND (category IS NULL)) OR ((action = 'IGNORE'::text) AND (category IS NULL) AND (commitment_id IS NULL))))
);


--
-- Name: merchant_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.merchant_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.merchant_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prices (
    instrument_id integer NOT NULL,
    price double precision NOT NULL,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    source text DEFAULT 'manual'::text NOT NULL
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text NOT NULL,
    value text
);


--
-- Name: snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snapshots (
    date text NOT NULL,
    value_rm double precision NOT NULL,
    cash_rm double precision NOT NULL,
    assets_rm double precision,
    liabilities_rm double precision,
    CONSTRAINT snapshots_owned_check CHECK ((((assets_rm IS NULL) OR (assets_rm >= (0)::double precision)) AND ((liabilities_rm IS NULL) OR (liabilities_rm >= (0)::double precision))))
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id integer NOT NULL,
    instrument_id integer NOT NULL,
    side text NOT NULL,
    qty double precision DEFAULT 0 NOT NULL,
    price double precision DEFAULT 0 NOT NULL,
    fees double precision DEFAULT 0 NOT NULL,
    amount double precision,
    trade_date text NOT NULL,
    source text DEFAULT 'manual'::text NOT NULL,
    ext_id text,
    CONSTRAINT transactions_side_check CHECK ((side = ANY (ARRAY['BUY'::text, 'SELL'::text, 'DIV'::text])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asset_entries asset_entries_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_entries
    ADD CONSTRAINT asset_entries_ext_id_key UNIQUE (ext_id);


--
-- Name: asset_entries asset_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_entries
    ADD CONSTRAINT asset_entries_pkey PRIMARY KEY (id);


--
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- Name: assets assets_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_slug_key UNIQUE (slug);


--
-- Name: broker_positions broker_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broker_positions
    ADD CONSTRAINT broker_positions_pkey PRIMARY KEY (instrument_id);


--
-- Name: card_plans card_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_plans
    ADD CONSTRAINT card_plans_pkey PRIMARY KEY (id);


--
-- Name: card_statements card_statements_commitment_id_statement_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_statements
    ADD CONSTRAINT card_statements_commitment_id_statement_date_key UNIQUE (commitment_id, statement_date);


--
-- Name: card_statements card_statements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_statements
    ADD CONSTRAINT card_statements_pkey PRIMARY KEY (id);


--
-- Name: card_transactions card_transactions_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_transactions
    ADD CONSTRAINT card_transactions_ext_id_key UNIQUE (ext_id);


--
-- Name: card_transactions card_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_transactions
    ADD CONSTRAINT card_transactions_pkey PRIMARY KEY (id);


--
-- Name: cash_movements cash_movements_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT cash_movements_ext_id_key UNIQUE (ext_id);


--
-- Name: cash_movements cash_movements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT cash_movements_pkey PRIMARY KEY (id);


--
-- Name: commitment_payments commitment_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commitment_payments
    ADD CONSTRAINT commitment_payments_pkey PRIMARY KEY (id);


--
-- Name: commitments commitments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commitments
    ADD CONSTRAINT commitments_pkey PRIMARY KEY (id);


--
-- Name: declared_rates declared_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.declared_rates
    ADD CONSTRAINT declared_rates_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_ext_id_key UNIQUE (ext_id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: fund_distributions fund_distributions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_distributions
    ADD CONSTRAINT fund_distributions_pkey PRIMARY KEY (instrument_id, ex_date);


--
-- Name: fund_metrics fund_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_metrics
    ADD CONSTRAINT fund_metrics_pkey PRIMARY KEY (instrument_id);


--
-- Name: fx_rates fx_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fx_rates
    ADD CONSTRAINT fx_rates_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: income_events income_events_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_events
    ADD CONSTRAINT income_events_ext_id_key UNIQUE (ext_id);


--
-- Name: income_events income_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_events
    ADD CONSTRAINT income_events_pkey PRIMARY KEY (id);


--
-- Name: income_sources income_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_sources
    ADD CONSTRAINT income_sources_pkey PRIMARY KEY (id);


--
-- Name: instruments instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);


--
-- Name: instruments instruments_ticker_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instruments
    ADD CONSTRAINT instruments_ticker_key UNIQUE (ticker);


--
-- Name: merchant_rules merchant_rules_pattern_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.merchant_rules
    ADD CONSTRAINT merchant_rules_pattern_key UNIQUE (pattern);


--
-- Name: merchant_rules merchant_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.merchant_rules
    ADD CONSTRAINT merchant_rules_pkey PRIMARY KEY (id);


--
-- Name: prices prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_pkey PRIMARY KEY (instrument_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- Name: snapshots snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snapshots
    ADD CONSTRAINT snapshots_pkey PRIMARY KEY (date);


--
-- Name: transactions transactions_ext_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_ext_id_key UNIQUE (ext_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: asset_entries_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX asset_entries_lookup_idx ON public.asset_entries USING btree (asset_id, date DESC);


--
-- Name: assets_product_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX assets_product_id_idx ON public.assets USING btree (product_id) WHERE (product_id IS NOT NULL);


--
-- Name: card_plans_card_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX card_plans_card_idx ON public.card_plans USING btree (commitment_id, started_on);


--
-- Name: card_statements_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX card_statements_lookup_idx ON public.card_statements USING btree (commitment_id, statement_date DESC);


--
-- Name: card_transactions_card_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX card_transactions_card_idx ON public.card_transactions USING btree (commitment_id, transacted_on);


--
-- Name: card_transactions_statement_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX card_transactions_statement_idx ON public.card_transactions USING btree (statement_id, transacted_on);


--
-- Name: cash_movements_instrument_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX cash_movements_instrument_id_idx ON public.cash_movements USING btree (instrument_id) WHERE (instrument_id IS NOT NULL);


--
-- Name: commitment_payments_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX commitment_payments_lookup_idx ON public.commitment_payments USING btree (commitment_id, date DESC);


--
-- Name: commitments_asset_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX commitments_asset_idx ON public.commitments USING btree (asset_id);


--
-- Name: commitments_collected_by_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX commitments_collected_by_idx ON public.commitments USING btree (collected_by_id);


--
-- Name: declared_rates_product_year_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX declared_rates_product_year_idx ON public.declared_rates USING btree (product_id, year);


--
-- Name: expenses_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX expenses_date_idx ON public.expenses USING btree (date DESC);


--
-- Name: fund_distributions_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX fund_distributions_lookup_idx ON public.fund_distributions USING btree (instrument_id, ex_date DESC);


--
-- Name: fx_rates_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX fx_rates_lookup_idx ON public.fx_rates USING btree (base, quote, date);


--
-- Name: income_events_lookup_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX income_events_lookup_idx ON public.income_events USING btree (source_id, date DESC);


--
-- Name: merchant_rules_match_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX merchant_rules_match_idx ON public.merchant_rules USING btree (length(pattern) DESC);


--
-- Name: asset_entries asset_entries_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_entries
    ADD CONSTRAINT asset_entries_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: broker_positions broker_positions_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.broker_positions
    ADD CONSTRAINT broker_positions_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id) ON DELETE CASCADE;


--
-- Name: card_plans card_plans_commitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_plans
    ADD CONSTRAINT card_plans_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id);


--
-- Name: card_statements card_statements_commitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_statements
    ADD CONSTRAINT card_statements_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id);


--
-- Name: card_transactions card_transactions_commitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_transactions
    ADD CONSTRAINT card_transactions_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id);


--
-- Name: card_transactions card_transactions_expense_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_transactions
    ADD CONSTRAINT card_transactions_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id);


--
-- Name: card_transactions card_transactions_statement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_transactions
    ADD CONSTRAINT card_transactions_statement_id_fkey FOREIGN KEY (statement_id) REFERENCES public.card_statements(id);


--
-- Name: cash_movements cash_movements_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_movements
    ADD CONSTRAINT cash_movements_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- Name: commitment_payments commitment_payments_commitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commitment_payments
    ADD CONSTRAINT commitment_payments_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id);


--
-- Name: commitments commitments_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commitments
    ADD CONSTRAINT commitments_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE SET NULL;


--
-- Name: commitments commitments_collected_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commitments
    ADD CONSTRAINT commitments_collected_by_id_fkey FOREIGN KEY (collected_by_id) REFERENCES public.commitments(id) ON DELETE SET NULL;


--
-- Name: expenses expenses_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: fund_distributions fund_distributions_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_distributions
    ADD CONSTRAINT fund_distributions_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- Name: fund_metrics fund_metrics_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_metrics
    ADD CONSTRAINT fund_metrics_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- Name: goals goals_asset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- Name: goals goals_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- Name: income_events income_events_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.income_events
    ADD CONSTRAINT income_events_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.income_sources(id);


--
-- Name: merchant_rules merchant_rules_commitment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.merchant_rules
    ADD CONSTRAINT merchant_rules_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id);


--
-- Name: prices prices_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prices
    ADD CONSTRAINT prices_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- Name: transactions transactions_instrument_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES public.instruments(id);


--
-- PostgreSQL database dump complete
--

